name       : libnspr
version    : 4.13.1
release    : 7
source     :
    - https://ftp.mozilla.org/pub/nspr/releases/v4.13.1/src/nspr-4.13.1.tar.gz : 5e4c1751339a76e7c772c0c04747488d7f8c98980b434dc846977e43117833ab
homepage   : http://www.mozilla.org
license    :
    - MPL-1.1
    - GPL-2.0
    - LGPL-2.1
component  : system.base
emul32     : yes
libsplit   : no
summary    : Netscape Portable Runtime
description: |
    Netscape Portable Runtime (NSPR) provides a platform-neutral API for system level and libc like functions.
setup      : |
    pushd nspr
    sed -i 's#$(LIBRARY) ##' config/rules.mk
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --prefix=/usr --with-mozilla --with-pthreads
    else
        %configure --prefix=/usr --enable-64bit  --with-mozilla --with-pthreads
    fi
build      : |
    pushd nspr
    %make
install    : |
    pushd nspr
    %make_install
    rm -v $installdir/usr/bin/prerr.properties
    rm -v $installdir/usr/bin/compile-et.pl
