name       : libnspr
version    : '4.19'
release    : 11
source     :
    - https://ftp.mozilla.org/pub/nspr/releases/v4.19/src/nspr-4.19.tar.gz : 2ed95917fa2277910d1d1cf36030607dccc0ba522bba08e2af13c113dcd8f729
homepage   : http://www.mozilla.org
license    :
    - MPL-1.1
    - GPL-2.0
    - LGPL-2.1
component  : system.base
emul32     : yes
libsplit   : no
summary    : Netscape Portable Runtime
description: |
    Netscape Portable Runtime (NSPR) provides a platform-neutral API for system level and libc like functions.
setup      : |
    pushd nspr
    sed -i 's#$(LIBRARY) ##' config/rules.mk
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --prefix=/usr --with-mozilla --with-pthreads
    else
        %configure --prefix=/usr --enable-64bit  --with-mozilla --with-pthreads
    fi
build      : |
    pushd nspr
    %make
install    : |
    pushd nspr
    %make_install
    rm -v $installdir/usr/bin/prerr.properties
    rm -v $installdir/usr/bin/compile-et.pl
