name       : libnspr
version    : '4.20'
release    : 12
source     :
    - https://ftp.mozilla.org/pub/nspr/releases/v4.20/src/nspr-4.20.tar.gz : 2c8964913da89ffbaf464d49ce44d79e8804e1794ef9a8c52a7bff7224d1556e
homepage   : https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR
license    :
    - MPL-1.1
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
emul32     : yes
libsplit   : no
summary    : Netscape Portable Runtime
description: |
    Netscape Portable Runtime (NSPR) provides a platform-neutral API for system level and libc like functions.
setup      : |
    cd nspr
    sed -i 's#$(LIBRARY) ##' config/rules.mk

    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --with-mozilla --with-pthreads
    else
        %configure --with-mozilla --with-pthreads --enable-64bit
    fi
build      : |
    %make -C nspr
install    : |
    %make_install -C nspr

    # We don't need this
    rm -v $installdir/usr/bin/prerr.properties
    rm -v $installdir/usr/bin/compile-et.pl
    rm -r $installdir/usr/include/nspr/md
