name        : libnspr
version     : 4.10.6
release     : 5
source      :
    - http://ftp.mozilla.org/pub/mozilla.org/nspr/releases/v4.10.6/src/nspr-4.10.6.tar.gz : df69ac8b0126f11907792384468adf42712b1d6db9772f4aa20c6d471594644a
homepage    : http://www.mozilla.org
license     :
    - MPL-1.1
    - GPL-2.0
    - LGPL-2.1
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32      : yes
libsplit    : no
summary     : Netscape Portable Runtime
description : |
    Netscape Portable Runtime (NSPR) provides a platform-neutral API for system level and libc like functions.
setup      : |
    pushd nspr
    sed -i 's#$(LIBRARY) ##' config/rules.mk
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --prefix=/usr --with-mozilla --with-pthreads
    else
        %configure --prefix=/usr --enable-64bit  --with-mozilla --with-pthreads
    fi
build      : |
    pushd nspr
    %make
install    : |
    pushd nspr
    %make_install
    rm -v $installdir/usr/bin/prerr.properties
    rm -v $installdir/usr/bin/compile-et.pl
